name: Linux CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        sudo apt-get update
        sudo apt-get install mono-complete
        dotnet tool install paket --global
        dotnet tool restore
        paket restore
        paket install
    - name: Build
      run: ./build.sh
    - name: Test
      run: dotnet test --no-build --verbosity normal
