name: Windows CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        dotnet tool restore
        dotnet paket install
    - name: Build
      run: ./build.cmd
    - name: Test
      run: dotnet test ./SQLProvider.Tests.sln --no-build --verbosity normal
